# Generated by Django 4.2.30 on 2026-08-28 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('etage', models.IntegerField()),
                ('nombre', models.IntegerField()),
                ('prix_heure', models.IntegerField()),
                ('prix_jour', models.IntegerField()),
                ('prix_mois', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, max_length=201, null=True)),
                ('reserver', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=40)),
                ('tel', models.IntegerField()),
                ('temps', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tarif', models.CharField(choices=[('jour', 'par jour'), ('heure', 'par heure'), ('mois', 'par mois')], default='jour', max_length=10)),
                ('total', models.DecimalField(decimal_places=0, max_digits=15)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=20)),
                ('secteur', models.CharField(max_length=20)),
                ('localisation', models.CharField(max_length=200)),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='photos_dhotel/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChambrePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos_dhotel/')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reservation.chambre')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='chambre',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.hotel'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
