# Generated by Django 4.2.30 on 2026-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
