# Generated by Django 4.2.30 on 2026-08-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_date_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='motif',
            field=models.CharField(choices=[('travail', 'pour le travail'), ('conge', 'pour un conge'), ('vacance', 'pour des vacances'), ('personnel', 'un cas personnel')], default='travail', max_length=15, null=True),
        ),
    ]
